// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// ); 
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALxz4h3pAtHCvH5eeD6E1prRSv01x3pjE',
    appId: '1:127951167078:web:4de09bfbe2af30a67057a7',
    messagingSenderId: '127951167078',
    projectId: 'proecommerce-80df6',
    authDomain: 'proecommerce-80df6.firebaseapp.com',
    storageBucket: 'proecommerce-80df6.firebasestorage.app',
    measurementId: 'G-QM8JVM0TT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMchmO-cAte7TkptiWXEKsgEM9w5QCcpE',
    appId: '1:127951167078:android:b15fe14d6f1cc6047057a7',
    messagingSenderId: '127951167078',
    projectId: 'proecommerce-80df6',
    storageBucket: 'proecommerce-80df6.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALxz4h3pAtHCvH5eeD6E1prRSv01x3pjE',
    appId: '1:127951167078:web:98f9e167af4c2d837057a7',
    messagingSenderId: '127951167078',
    projectId: 'proecommerce-80df6',
    authDomain: 'proecommerce-80df6.firebaseapp.com',
    storageBucket: 'proecommerce-80df6.firebasestorage.app',
    measurementId: 'G-YJ27YBH9VJ',
  );
}
